version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4.0
  python: circleci/python@2.0.3

docker-auth: &docker-auth
  auth:
    username: ${DOCKERHUB_USER}
    password: ${DOCKERHUB_PASSWORD}

commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"
jobs:
  deploy:
    resource_class: small
    docker:
      - image: cimg/aws:2025.01.1
        <<: *docker-auth
    steps:
      - greeting:
          to: 'Mister Guide'
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          region: ${AWS_DEFAULT_REGION}
          role_session_name: "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}"
          session_duration: "3600"
      - run:
          name: Perform some AWS actions
          command: |
            # See who we are
            aws --no-cli-pager sts get-caller-identity
            # List buckets
            aws s3 ls
#      - run:
#          name: Install python3.10-venv
#          command: |
#            sudo apt-get update || :
#            sudo apt -y install python3.10-venv
#      - run:
#          name: Create Virtual Environment
#          command: |
#            chmod 755 create_venv.sh
#            ./create_venv.sh
      - run:
          name: Test
          command: |
#            . .venv/bin/activate
            python example.py

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          context:
            - banana
      - pause_workflow:
          requires:
            - deploy
          type: approval
